### ISSUE TITLE
how much the NavX is drifting

### ISSUE THREAD

**Issue by wmbelk** [Team2556/Crescendo#12]
Next is field-centric, which should ideally tell us how much the NavX is drifting. If it is an insane amount of drift then we can look into april tags always resetting the robot's position in order to compensate for the drift.

**Comment by NawaPlayz** [comment]
NavX still had significant drift, so looking in to using april tags to correct drift is definitely necessary.  Here are a couple of links that provide some useful information on the topic. Using the UI to visualize the gyro could possibly be helpful. I plan to look in to instances of other teams having drift issues and if they resolved it.
https://pdocs.kauailabs.com/navx-mxp/guidance/gyroaccelcalibration/
https://docs.wsr.studica.com/en/latest/docs/VMX/navx.html#best-practices
