### ISSUE TITLE
Tweak pathplanner, with functional swerve drive

### ISSUE THREAD

**Issue by wmbelk** [Team2556/Crescendo#16]
- [x] Test pathplanner with functional swerve drive and see how the paths for a basic autonomous need to be tweaked.
- [x] Tweak auto paths

**Comment by NawaPlayz** [comment]
Pathplanner worked great. Next step is to have the paths from 3 different start positions. These starting positions should be against the subwoofer on the amp's side, another in front of the subwoofer, and another by the opposing team's human player station. Ideally have a path for leaving the wing, another that grabs a note and then leaves, another that grabs 2 notes then leaves, and another that grabs all 3 notes and leaves. Make sure there is a path for all of those configurations for all 3 starting positions. If there is extra time then include a path to grab a center note and figure out how much time is remaining. 

Current constraints are 4.5 m/s velocity & 7 m/s acceleration
